# Support the author by using the funding link below
# Developed and maintained by Kadir Metin
# Buy Me a Coffee: https://buymeacoffee.com/kadirmetin

buy_me_a_coffee: kadirmetin

#Your support means a lot to me to continue the development of open source project like this.